### PR TITLE
fix: fix navigation while state is loading

### LINKED ISSUE #364: Fix navigation when UI state is loading
Allow the user to navigate between screens before the whole ui state loads. Example: right now, the user has to wait for the home screen's posts to load before being able to navigate to their profile.

### PR DESCRIPTION
**Pull request by leolmr1110**
## Description
This PR fixes a navigation design flaw in some top level screens, the Home screen, the Collection screen and the Report screen. The flaw resided in the fact that the top bar of these screens allows in theory to navigate to the current user's profile page but the navigation was only possible after loading the UI state from the view model, which didn't really make sense. For example, on the Home screen, you had to wait for the posts to load before you could navigate to the current user's profile page without an error occurring.

I deleted the `HomeTopBar` and the `ReportScreenTopBar`, and I changed the `CollectionScreenTopBar`. They were replaced by a modular version `TopLevelTopBar`. 

I added a screen parameter `onCurrentProfilePictureClick` to the Home screen and the Report screen which is passed to the `TopLevelTopBar` for redirection to the current user's profile page.

I modified the ViewModel of the three screens to load the user faster and independently of the rest of the screen's state. This allows for faster current user profile picture loading.

## Related issues
Closes #364

### CODE REVIEW

File: app/src/main/java/com/android/wildex/ui/navigation/TopLevelTopBar.kt [hunk 1]
```diff
@@ -25,42 +19,43 @@ import androidx.compose.ui.Modifier
...
-    onProfilePictureClick: (userId: Id) -> Unit,
+fun TopLevelTopBar(
+    currentUser: SimpleUser,
+    title: String,
+    onNotificationClick: () -> Unit = {},
+    onProfilePictureClick: () -> Unit = {}
 ) {
   TopAppBar(
       title = {
         Box(
```
Comment (youssef-9511) [inline app/src/main/java/com/android/wildex/ui/navigation/TopLevelTopBar.kt]: No need for the `Box` here, for centering you can use `CenterAlignedTopAppBar` for centering.

**Review by youssef-9511 — APPROVED** [review]
I have no comment on your implementation, the fix is good. I did suggest some cleanup changes however, but since it's not technically your code I'll approve this. Nice job!
