### PR TITLE
fix: Refactor the comment data class and repository

### LINKED ISSUE #196: Refactor Comment data class
We need to introduce a new enum called `CommentTag` with two values:

* `POST_COMMENT` → for comments related to posts
* `REPORT_COMMENT` → for comments related to reports

Then, add a new `tag` field of type `CommentTag` in the `Comment` data class.
This field should have a default value of `POST_COMMENT` so that the existing code keeps working without any breaking changes.

Also, add two new methods in the `CommentRepository` and their respective tests to maintain coverage:

* `deleteAllCommentsOfPost(postId)`
* `deleteAllCommentsOfReport(reportId)`

### Why

Right now, all comments are treated the same way, but we’ll soon need to distinguish between comments on posts and comments on reports.
When a report gets deleted, all its comments should be deleted too.
The same logic applies if we later add the option to delete a post , its comments should be removed as well.
Having a `tag` field and the new repository methods makes this behavior clear and easy to handle.

### PR DESCRIPTION
**Pull request by MartZimm21**
## Description
This PR adds two functions to the `CommentsRepository` interface, their implementation in `CommentsRepositoryFirestore` along with new tests in `CommentsRepositoryFirestoreTest`.

These new functions provide the following operations:
- deleteAllCommentsOfPost(postId): Deletes all comments of a post
- deleteAllCommentsOfReport(reportId): Deletes all comments of a report

This required to add a tag to the `Comment` data class, specifying if a comment is related to a `Post` or a `Report`, so that we can differentiate a `Post` with a `Report` in case they have the same Id - which is possible since they come from different collections.

This implied necessary changes in every file related to Comments, so they could handle this new tag.

Some changes were also made to use the alias Id instead of String, for better clarity.

## Related issues
Closes #196 

## How to test
1. Start the Firestore Emulator: `firebase emulators:start`
2. Run `CommentRepositoryFirestoreTest.kt`

### CODE REVIEW

File: app/src/main/java/com/android/wildex/model/social/Comment.kt [hunk 1]
```diff
@@ -10,12 +10,20 @@ import com.google.firebase.Timestamp
  * @property postId The ID of the post that this comment belongs to.
  * @property authorId The ID of the user who made the comment.
  * @property text The content of the comment.
- * @property date The date and time when the comment was made.
+ * @property date The date and time when the comment was made. //@property tag The tag of the
+ *   comment.
```
Comment (JonathanPilemand) [inline app/src/main/java/com/android/wildex/model/social/Comment.kt]: Seems like the // are a typo here. This is cleaner:

```suggestion
 * @property date The date and time when the comment was made. 
 * @property tag The tag of the comment.
```

File: app/src/main/java/com/android/wildex/model/social/Comment.kt [hunk 2]
```diff
@@ -10,12 +10,20 @@ import com.google.firebase.Timestamp
...
  */
 data class Comment(
     val commentId: Id,
     val postId: Id,
```
Comment (JonathanPilemand) [inline app/src/main/java/com/android/wildex/model/social/Comment.kt]: To avoid confusion between comments from post and reports, I think we need to rename this `parentId`


```suggestion
    val parentId: Id,
```

**Review by JonathanPilemand — CHANGES_REQUESTED** [review]
This looks good overall. 
One issue is just that with the new test tag, it makes more sense to rename the `postId` field of the `Comment` data class to `parentId`. This is to avoid confusion, since posts and reports use the same get function, which means in case of id collision, the caller of this get function can filter from all types on the parent, using the test tag. It's not just a get function for the comments of a `Post`
Attention: this does mean however, that there's a lot of files that need refactoring because of these name changes. More than the suggested changes shown here.

**Comment by MartZimm21** [comment]
> This looks good overall. One issue is just that with the new test tag, it makes more sense to rename the `postId` field of the `Comment` data class to `parentId`. This is to avoid confusion, since posts and reports use the same get function, which means in case of id collision, the caller of this get function can filter from all types on the parent, using the test tag. It's not just a get function for the comments of a `Post` Attention: this does mean however, that there's a lot of files that need refactoring because of these name changes. More than the suggested changes shown here.

I totally agree, but this will require changes in many files so I suggest doing it in a separate PR.
